name: Deploy to EC2 from GHCR

on:
  workflow_dispatch:
  registry_package:
    types: [published, updated]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy container on EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          VIRTUAL_HOST: ${{ secrets.VIRTUAL_HOST }}
          LETSENCRYPT_HOST: ${{ secrets.LETSENCRYPT_HOST }}
          LETSENCRYPT_EMAIL: ${{ secrets.LETSENCRYPT_EMAIL }}
        run: |
          ssh -o BatchMode=yes -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            set -xe

            # Log in to GHCR
            echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Pull the main branch image
            sudo docker pull ghcr.io/${{ github.repository }}:main

            # Stop and remove any existing container
            if sudo docker ps -q -f name=smartpapers-frontend; then
              sudo docker stop smartpapers-frontend
            fi
            if sudo docker ps -aq -f name=smartpapers-frontend; then
              sudo docker rm smartpapers-frontend
            fi

            # Run the new container
            sudo docker run -d \
              --name smartpapers-frontend \
              --restart unless-stopped \
              --env-file .env \
              --network proxy-net \
              -e VIRTUAL_HOST=$VIRTUAL_HOST \
              -e LETSENCRYPT_HOST=$LETSENCRYPT_HOST \
              -e LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL \
              ghcr.io/${{ github.repository }}:main
          EOF
